source 'https://rubygems.org'

gem 'bourbon'
gem 'image_optim'
gem 'middleman', '~> 4.0'
gem 'middleman-autoprefixer'
gem 'middleman-deploy', '= 2.0.0.pre.alpha'
gem 'middleman-livereload', '~> 3.4'
gem 'middleman-search_engine_sitemap'
gem 'middleman-sprockets', '~> 4.0.0'
gem 'overcommit'
gem 'sassc', '~> 1.8'
gem 'scss-lint'
gem 'slim'
