source 'https://rubygems.org'

gem 'bourbon', '~> 4.2'
gem 'middleman', '~> 4.0'
gem 'middleman-autoprefixer', '~> 2.6'
gem 'middleman-deploy', '= 2.0.0.pre.alpha'
gem 'middleman-livereload', '~> 3.4'
gem 'middleman-search_engine_sitemap'
gem 'middleman-sprockets', '~> 4.0.0'
gem 'neat', '~> 1.7'
gem 'sassc', '~> 1.8'
gem 'slim'
